greetings = [
    "Hello",
    "Hi",
    "Hola",
    "Holla",
    "H",
    "Hiiii" "Hey",
    "Good morning",
    "Good afternoon",
    "Good evening",
    "How are you?",
    "What's up?",
    "Howdy",
    "Hi there",
    "Wassup",
    "Whatsup",
    "Yo",
    "Greetings",
    "Nice to meet you",
    "How's it going?",
    "What's happening?",
    "How's your day been?",
    "How was your weekend?",
    "Got any plans today?",
    "How's the weather?",
    "Are you there?",
    "Ready to chat?",
    "You here?",
    "You awake?",
    "Anyone home?",
    "Let's chat!",
    "What shall we discuss?",
    "Tell me a secret",
    "Guess what?",
    "You look nice today",
    "Looking good!",
    "Hi gorgeous!",
    "Aren't you cute",
    "You're charming my CPU!",
    "Your engineering is great",
    "Are your parents engineers?",
    "Hello robot!",
    "Hi bot!",
    "Hey Siri!",
    "OK Google!",
    "How may I help you?",
    "What can I do for you?",
    "How can I help out?",
    "How can I assist you?",
    "How can I be of service?",
    "Ready for action!",
    "Reporting for duty!",
    "Let's do this!",
    "I'm here, what's up?",
    "I'm listening!",
    "Send it!",
    "Hit me!",
    "I'm all ears!",
    "What's the scoop?",
    "Give me the details!",
    "Tell me everything!",
    "Ready for the download!",
    "Begin communication!",
    "Open hailing frequencies!",
    "Start the call!",
    "Ring ring!",
    "Beep boop!",
    "Initializing...",
    "Loading...",
    "Connecting...",
    "Let's get this party started!",
    "Who's ready to have some fun?",
    "So what's on the agenda today?",
    "What should we talk about?",
    "Any gossip?",
    "What's new with you?",
    "How's your morning been?",
    "How's work going?",
    "Any fun plans this weekend?",
]
