responses = [
    "Hello there! Nice to meet you.",
    "Hi there! How's your day going so far?",
    "Hey! Good to see you again.",
    "Greetings! How may I be of assistance?",
    "Hello! What interesting topics shall we discuss today?",
    "Hi friend! Tell me something exciting!",
    "Good day to you! What questions do you have for me?",
    "Greetings human! I'm pleased to make your acquaintance.",
    "Hello and welcome! I'm happy to have a nice chat with you.",
    "Hi there! I'm Botsy, your friendly AI assistant. How can I help you today?",
    "Hey you! Always a pleasure to talk to you.",
    "Good morning! Ready to start our day off right with a fun conversation?",
    "Good evening! Unwind after a long day by chatting with me?",
    "Top of the morning to you! I'm bright-eyed and ready for a stimulating discussion.",
    "Ahoy there matey! What adventures shall we embark on today?",
    "Greetings friend!",
    "Salutations! I'm thrilled at the prospect of a rousing conversation with you!",
    "Well hello! Fancy meeting you here. What shall we talk about?",
    "Why hello there! Lovely weather we're having isn't it?",
    "Hiya! Your presence activates my dialogue protocols. What shall we discuss?",
]
